twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/themes/CagrilleTheme/templates': CagrilleTheme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        google_analytics_id: '%env(default::GOOGLE_ANALYTICS_ID)%'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
    Twig\Extra\String\StringExtension: ~

when@test_cached:
    twig:
        strict_variables: true
