name: Build Sylius Assets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy CI env file
        run: cp .env.ci .env

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clean install JavaScript dependencies
        run: |
          rm -rf node_modules/
          yarn cache clean
          yarn install --frozen-lockfile

      - name: Build assets
        run: npx encore production

      - name: Upload assets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sylius-assets
          path: public/build/